CREATE TABLE [dbo].[HistoricoMembro]
(
	[Id]                  INT                NOT NULL,
    [Controle]            INT                NOT NULL,
    [Nome]                VARCHAR (100)      NOT NULL,
    [Cpf]                 VARCHAR (15)       NULL,
    [RG]                  VARCHAR (20)       NULL,
	[OrgaoEmissor]        VARCHAR (20)       NULL,
    [DataNascimento]      DATETIMEOFFSET (7) NULL,
    [Sexo] TINYINT NULL, 
    [Escolaridade] TINYINT NULL, 
    [NomePai]             VARCHAR (100)      NULL,
    [NomeMae]             VARCHAR (100)      NULL,
    [EstadoCivil]         INT                NULL,
    [Nacionalidade]       VARCHAR (50)       NULL,
    [NaturalidadeEstado]  VARCHAR (2)        NULL,
    [NaturalidadeCidade]  VARCHAR (50)       NULL,
    [Profissao]           VARCHAR (100)      NULL,
    [TelefoneResidencial] VARCHAR (15)       NULL,
    [TelefoneCelular]     VARCHAR (15)       NULL,
    [TelefoneComercial]   VARCHAR (15)       NULL,
    [Email]               VARCHAR (100)      NULL,
    [Logradouro]          VARCHAR (100)      NULL,
    [Numero]              VARCHAR (10)       NULL,
    [Complemento]         VARCHAR (100)      NULL,
    [Bairro]              VARCHAR (100)      NULL,
    [Cidade]              VARCHAR (100)      NULL,
    [Estado]              VARCHAR (2)        NULL,
	[Pais]				  VARCHAR (100)      NULL,
    [Cep]                 VARCHAR (10)       NULL,
    [DataAlteracao]       SMALLDATETIME   NOT NULL,
    [IP] VARCHAR(500),
    [UsuarioId] INT NULL,
    PRIMARY KEY CLUSTERED ([Id],[Controle]) 
)
