CREATE TABLE [dbo].[Membro] (
    [Id]                  INT                NOT NULL,
    [CongregacaoId]       INT                NOT NULL,
    [Nome]                VARCHAR (100)      NOT NULL,
    [Cpf]                 VARCHAR (15)       NULL,
    [RG]                  VARCHAR (20)       NULL,
	[OrgaoEmissor]        VARCHAR (20)       NULL,
    [DataNascimento]      DATETIMEOFFSET (7) NULL,
    [IdPai] INT NULL, 
    [NomePai]             VARCHAR (100)      NULL,
    [IdMae] INT NULL, 
    [NomeMae]             VARCHAR (100)      NULL,
    [EstadoCivil]         INT                NULL,
    [Nacionalidade]       VARCHAR (50)       NULL,
    [NaturalidadeEstado]  VARCHAR (2)        NULL,
    [NaturalidadeCidade]  VARCHAR (50)       NULL,
    [Profissao]           VARCHAR (100)      NULL,
    [TituloEleitorNumero] VARCHAR (30)       NULL,
    [TituloEleitorZona]   VARCHAR (30)       NULL,
    [TituloEleitorSecao]  VARCHAR (30)       NULL,
    [TelefoneResidencial] VARCHAR (15)       NULL,
    [TelefoneCelular]     VARCHAR (15)       NULL,
    [TelefoneComercial]   VARCHAR (15)       NULL,
    [Email]               VARCHAR (100)      NULL,
    [FotoPath]            VARCHAR (MAX)      NULL,
    [Logradouro]          VARCHAR (100)      NULL,
    [Numero]              VARCHAR (10)       NULL,
    [Complemento]         VARCHAR (100)      NULL,
    [Bairro]              VARCHAR (100)      NULL,
    [Cidade]              VARCHAR (100)      NULL,
    [Estado]              VARCHAR (30)        NULL,
	[Pais]				  VARCHAR (100)      NULL,
    [Cep]                 VARCHAR (15)       NULL,
    [RecebidoPor]         INT                NULL,
    [DataRecepcao]        DATETIMEOFFSET (7) NULL,
    [DataBatismoAguas]    DATETIMEOFFSET (7) NULL,
	[DataPrevistaBatismo] DATETIMEOFFSET (7) NULL,
    [BatimoEspiritoSanto] BIT                NULL,
    [ABEDABE]             BIT                NULL,  
    [CriadoPorId]         INT                NOT NULL,
    [AprovadoPorId]       INT                NULL,
    [Status]              INT                NOT NULL,
    [TipoMembro]          INT                NULL,
    [DataCriacao]         DATETIMEOFFSET (7) NOT NULL,
    [DataAlteracao]       DATETIMEOFFSET (7) NOT NULL,
    [IdConjuge]			  INT                NULL,
    [NomeConjuge] VARCHAR(100) NULL, 
    [BatismoId]			  INT				 NULL, 
    [BatismoSituacao]	  INT				 NULL, 
    [DataValidadeCarteirinha] DATETIMEOFFSET NULL, 
    [CartaId]			  INT NULL, 
    [Sexo] TINYINT NULL, 
    [Escolaridade] TINYINT NULL, 
    [FotoUrl] VARCHAR(500) NULL, 
    [TamanhoCapa] VARCHAR(2) NULL, 
    [Senha] VARCHAR(1000) NULL, 
    [AtualizarSenha] BIT NULL, 
    CONSTRAINT [FK_Membro_Congregacao] FOREIGN KEY (CongregacaoId) REFERENCES Congregacao(Id),
    PRIMARY KEY CLUSTERED ([Id] ASC)
);







