CREATE PROCEDURE ListarCandidatosBatismoPaginada
	@PAGESIZE INT,
	@ROWSTART INT,
	@SORTING VARCHAR(30),
	@USUARIOID INT,
	@CAMPO VARCHAR(255) = NULL,
	@VALOR VARCHAR(255) = NULL
AS
BEGIN
	SET NOCOUNT ON
	DECLARE 
		@SQLQUERY NVARCHAR(4000),
		@PARMDEFINITION NVARCHAR(500),
		@ORDERBY NVARCHAR(400),
		@SQLFILTRO NVARCHAR(4000)
	

	IF OBJECT_ID('TEMPDB..#CONGR') IS NOT NULL 
		DROP TABLE #CONGR
	CREATE Table #CONGR (CongregacaoId INT NOT NULL) 
	
	INSERT INTO #CONGR
	SELECT * FROM dbo.CongregacaoAcesso(@UsuarioId, default)
	
	IF (CHARINDEX('CongregacaoNome', @SORTING) > 0)
		SET @ORDERBY = REPLACE(@SORTING, 'CongregacaoNome', 'C.Nome')
	ELSE
		SET @ORDERBY = 'M.' + @SORTING

	SET @SQLFILTRO = ''	
	IF (NULLIF(@VALOR,'') IS NOT NULL)
	BEGIN
		IF (@CAMPO = 'CongregacaoId')
			SET @SQLFILTRO = ' AND (C.Id = @VALOR)'
		ELSE
			SET @SQLFILTRO = ' AND M.' + @CAMPO  + ' LIKE ''%' + @VALOR + '%'' COLLATE Latin1_General_CI_AI'
	END
	
	
	SET @SQLQUERY =
		'SELECT TOP(@PAGESIZE) * FROM (' +
		'	SELECT '+
		'		M.Id, C.Nome AS CongregacaoNome, M.Nome, M.NomeMae,'+
		'		M.Cpf, M.DataNascimento, M.BatismoId, '+
		'		ROW_NUMBER() OVER (ORDER BY ' + @ORDERBY + ') AS NUM '+
		'	FROM'+
		'		Membro M WITH(NOLOCK)'+
		'	INNER JOIN Congregacao C WITH(NOLOCK) ON M.CongregacaoId = C.Id'+
		'	WHERE'+
		'		M.BatismoId IN (SELECT B.Id FROM Batismo B WITH(NOLOCK) WHERE B.Status = 1)'+
		@SQLFILTRO +
		'		AND M.CongregacaoId IN (SELECT * FROM #CONGR)'+
		'		AND M.TipoMembro = 2'+
		'		AND M.Status = 1) AS A '+
		'WHERE '+
			'NUM > @ROWSTART '

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/
	SET @SQLQUERY = @SQLQUERY + ' ORDER BY A.' + @SORTING

	/* EXECUCAÇÃO DA QUERY */
	SET @PARMDEFINITION = '@PAGESIZE INT, @ROWSTART INT, @VALOR VARCHAR(255), @USUARIOID INT'
	EXECUTE SP_EXECUTESQL @SQLQUERY, @PARMDEFINITION, @PAGESIZE, @ROWSTART, @VALOR, @USUARIOID

	/*RETORNA A QUANTIDADE DE LINHAS TOTAIS COM O FILTRO*/
	DECLARE @SQLCOUNT NVARCHAR(4000)

	SET @SQLCOUNT = 		
		'	SELECT COUNT(*)	FROM Membro M WITH(NOLOCK)'+
		'	INNER JOIN Congregacao C WITH(NOLOCK) ON M.CongregacaoId = C.Id'+
		'	WHERE'+
		'		M.BatismoId IN (SELECT B.Id FROM Batismo B WITH(NOLOCK) WHERE B.Status = 1)'+
		@SQLFILTRO +
		'		AND M.CongregacaoId IN (SELECT * FROM #CONGR)'+
		'		AND M.TipoMembro = 2'+
		'		AND M.Status = 1 --ATIVO'

	EXECUTE SP_EXECUTESQL @SQLCOUNT, @PARMDEFINITION,@PAGESIZE, @ROWSTART, @VALOR, @USUARIOID
END