CREATE PROCEDURE ListarBatismoPaginada
	@PAGESIZE INT,
	@ROWSTART INT,
	@SORTING VARCHAR(30)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE 
		@SQLQUERY NVARCHAR(4000),
		@PARMDEFINITION NVARCHAR(500)

	IF (ISNULL(@SORTING, '') = '')
		SELECT @SORTING = 'DataBatismo DESC'

	SET @SQLQUERY =
		'SELECT TOP(@PAGESIZE) * FROM (' +
		'	SELECT '+
		'		B.Id, B.DataMaximaCadastro, B.DataBatismo, B.Status, '+ 
		'		ROW_NUMBER() OVER (ORDER BY B.' + @SORTING + ') AS NUM '+
		'	FROM'+
		'		Batismo B WITH(NOLOCK)' +
		') AS A '+
		'WHERE '+
			'NUM > @ROWSTART '

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/
	SET @SQLQUERY = @SQLQUERY + ' ORDER BY A.' + @SORTING

	/* EXECUCAÇÃO DA QUERY */
	SET @PARMDEFINITION = '@PAGESIZE INT, @ROWSTART INT'
	EXECUTE SP_EXECUTESQL @SQLQUERY, @PARMDEFINITION, @PAGESIZE, @ROWSTART

	/*RETORNA A QUANTIDADE DE LINHAS TOTAIS COM O FILTRO*/
	DECLARE @SQLCOUNT NVARCHAR(4000)

	SET @SQLCOUNT =  'SELECT COUNT(*) FROM Batismo B WITH(NOLOCK)'
	EXECUTE SP_EXECUTESQL @SQLCOUNT, @PARMDEFINITION,@PAGESIZE, @ROWSTART
END