CREATE PROCEDURE [dbo].[BuscarCongregacoes]
	@PAGESIZE INT,
	@ROWSTART INT,
	@SORTING VARCHAR(60),
	@CAMPO VARCHAR(255) = NULL,
	@VALOR VARCHAR(255) = NULL,
	@USUARIOID INT = NULL
AS
BEGIN
	SET NOCOUNT ON
	DECLARE 
		@SQLQUERY NVARCHAR(4000),
		@SQLFILTO NVARCHAR(4000),
		@PARMDEFINITION NVARCHAR(500),
		@SQLFILTROAUX NVARCHAR(4000),
		@ORDERBY NVARCHAR(400)

/* CONFIGURAÇÃO DO FILTRO */
	SET @SQLFILTO = ''
	SET @ORDERBY = @SORTING
			
	IF (NULLIF(@VALOR,'') IS NOT NULL)
	BEGIN
		IF(@CAMPO = 'Id' AND NULLIF(@VALOR,'') IS NOT NULL)
			SET @SQLFILTO = @SQLFILTO + ' AND (Id = CONVERT(INT, @VALOR))'
		ELSE IF(@CAMPO = 'Nome')
		BEGIN
			SET @SQLFILTO = @SQLFILTO + ' AND Nome LIKE ''%' + @VALOR + '%'' COLLATE Latin1_General_CI_AI'
			SET @ORDERBY = 'Nome'
		END
	END

	SET @SQLQUERY =
	'SELECT TOP(@PAGESIZE) * FROM (' +
		'SELECT '+
		'C.Id, C.Nome, ROW_NUMBER() OVER (ORDER BY ' + @ORDERBY + ') AS NUM '+
		'FROM Congregacao C WITH(NOLOCK) ' + 
		'WHERE '+
		' Id IN (SELECT * FROM dbo.CongregacaoAcesso(@USUARIOID, default)) ' + 
		' AND C.Situacao = 1 '
		+ @SQLFILTO +
	') AS A '+
	'WHERE '+
		'NUM > @ROWSTART '

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/
	SET @SQLQUERY = @SQLQUERY + ' ORDER BY A.' + @ORDERBY

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/

	/* EXECUCAÇÃO DA QUERY */
	SET @PARMDEFINITION = '@PAGESIZE INT, @ROWSTART INT, @VALOR VARCHAR(255), @USUARIOID INT'
	EXECUTE SP_EXECUTESQL @SQLQUERY, @PARMDEFINITION, @PAGESIZE, @ROWSTART, @VALOR, @USUARIOID


	--/*RETORNA A QUANTIDADE DE LINHAS TOTAIS COM O FILTRO*/
	DECLARE @SQLCOUNT NVARCHAR(4000)
	SET @SQLCOUNT = 'SELECT COUNT(*) AS ROWSCOUNT FROM Congregacao WITH(NOLOCK) '
    SET @SQLCOUNT = @SQLCOUNT + ' WHERE Id IN (SELECT * FROM dbo.CongregacaoAcesso(@USUARIOID, default)) AND Situacao = 1 '+ @SQLFILTO
	EXECUTE SP_EXECUTESQL @SQLCOUNT, @PARMDEFINITION,@PAGESIZE, @ROWSTART, @VALOR, @USUARIOID

END