CREATE PROCEDURE ListarCongregacaoPaginada
	@PAGESIZE INT,
	@ROWSTART INT,
	@SORTING VARCHAR(60),
	@USUARIOID INT,
	@CAMPO VARCHAR(255) = NULL,
	@VALOR VARCHAR(255) = NULL
AS
BEGIN
	SET NOCOUNT ON
	DECLARE 
		@SQLQUERY NVARCHAR(4000),
		@PARMDEFINITION NVARCHAR(500),
		@SQLFILTROAUX NVARCHAR(4000),
		@ORDERBY NVARCHAR(400),
		@FILTRO NVARCHAR(4000)


	/* CONFIGURAÇÃO DO FILTRO */
	SET @FILTRO = ''
	
	IF (NULLIF(@VALOR,'') IS NOT NULL)
	BEGIN
		IF (@CAMPO = 'Pastor')
			SET @FILTRO = @FILTRO + ' AND M.Nome LIKE ''%' + @VALOR + '%'' COLLATE Latin1_General_CI_AI'
		ELSE
			SET @FILTRO = @FILTRO + ' AND C.' + @CAMPO + ' LIKE ''%' + @VALOR + '%'' COLLATE Latin1_General_CI_AI'
	END

	SET @ORDERBY = 'C.' + ISNULL(@SORTING, 'C.Id') 
	IF (CHARINDEX('CongregacaoResponsavelNome', @ORDERBY) > 0)
		SET @ORDERBY = REPLACE (@ORDERBY, 'C.CongregacaoResponsavelNome', 'C1.Nome')
	ELSE IF(CHARINDEX('PastorResponsavelNome', @ORDERBY) > 0)
		SET @ORDERBY = REPLACE (@ORDERBY, 'C.PastorResponsavelNome', 'M.Nome')

	SET @SQLQUERY =
		'SELECT TOP(@PAGESIZE) * FROM (' +
		'	SELECT '+
		'		C.Id, C.Nome'+
		'		, C1.Nome AS CongregacaoResponsavelNome'+
		'		, M.Nome AS PastorResponsavelNome'+
		'	   , ROW_NUMBER() OVER (ORDER BY ' + @ORDERBY + ') AS NUM '+
		'	FROM Congregacao C WITH(NOLOCK) '+
		'	LEFT JOIN Membro M WITH(NOLOCK) ON M.Id = C.PastorResponsavelId '+
		'	LEFT JOIN Congregacao C1 WITH(NOLOCK) ON C1.Id = ISNULL(C.CongregacaoResponsavelId, (SELECT Id FROM dbo.Congregacao WHERE Sede = 1))' +
		'	WHERE ' +
		'	 C.Id IN (SELECT * FROM dbo.CongregacaoAcesso(@USUARIOID, default)) AND C.Situacao = 1 ' +
		@FILTRO + 
		'	) AS A '+
		'WHERE '+
		'	NUM > @ROWSTART '
	/* CONFIGURAÇÃO DA ORDENAÇÃO*/
	SET @SQLQUERY = @SQLQUERY + ' ORDER BY A.' + ISNULL(@SORTING, 'Id') 

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/

	/* EXECUCAÇÃO DA QUERY */
	SET @PARMDEFINITION = '@PAGESIZE INT, @ROWSTART INT, @USUARIOID INT'
	EXECUTE SP_EXECUTESQL @SQLQUERY, @PARMDEFINITION, @PAGESIZE, @ROWSTART, @USUARIOID

	--/*RETORNA A QUANTIDADE DE LINHAS TOTAIS COM O FILTRO*/
	DECLARE @SQLCOUNT NVARCHAR(4000)
	SET @SQLCOUNT = 'SELECT COUNT(*) AS ROWSCOUNT FROM Congregacao C WITH(NOLOCK) '
    SET @SQLCOUNT = @SQLCOUNT + '	LEFT JOIN Membro M WITH(NOLOCK) ON M.Id = C.PastorResponsavelId '
    SET @SQLCOUNT = @SQLCOUNT + ' WHERE C.Id IN (SELECT * FROM dbo.CongregacaoAcesso(@USUARIOID, default)) AND C.Situacao = 1 ' + @FILTRO
	EXECUTE SP_EXECUTESQL @SQLCOUNT, @PARMDEFINITION,@PAGESIZE, @ROWSTART, @USUARIOID

END