CREATE PROCEDURE RelMensalCasamento
	@Mes TINYINT, 
	@Ano INT, 
	@CongregacaoId INT
AS
BEGIN
	DECLARE @DataIni DATETIMEOFFSET, @DataFim DATETIMEOFFSET
	EXEC Util_RetornaPeriodoMes @Mes, @Ano, @DataIni OUTPUT, @DataFim OUTPUT

	SELECT 
		CASE WHEN C.NOIVOID IS NOT NULL THEN 
			(SELECT Y.NOME  FROM CASAMENTO X INNER JOIN MEMBRO Y ON X.NOIVOID = Y.ID WHERE C.DATAHORAINICIO = X.DATAHORAINICIO)
		ELSE 
			C.NOIVONOME 
		END AS NoivoNome,
		CASE WHEN C.NOIVAID IS NOT NULL THEN 
			(SELECT Y.NOME  FROM CASAMENTO X INNER JOIN MEMBRO Y ON X.NOIVAID = Y.ID WHERE C.DATAHORAINICIO = X.DATAHORAINICIO)
		ELSE 
			C.NOIVANOME 
		END AS NoivaNome,
		CASE WHEN C.PASTORID <> 0 THEN 
			(SELECT Y.NOME  FROM CASAMENTO X INNER JOIN MEMBRO Y ON X.PASTORID = Y.ID WHERE C.DATAHORAINICIO = X.DATAHORAINICIO)
		ELSE 
			C.PASTORNOME 
		END AS PastorNome, 
	    C.DataHoraInicio AS Data
	FROM 
		Casamento C 
	WHERE 
		C.DataHoraInicio >= @DataIni 
		AND C.DataHoraFinal <= @DataFim
		AND C.CongregacaoId = @CongregacaoId
END