CREATE PROCEDURE [dbo].[Util_RetornaPeriodoMes]
	@Mes TINYINT, 
	@Ano INT,
	@DataIni DATETIMEOFFSET OUTPUT,
	@DataFim DATETIMEOFFSET OUTPUT
AS
BEGIN
	DECLARE @UltDia CHAR(2)
	SELECT @DataIni = CONVERT(DATETIMEOFFSET, CONCAT(@Ano, '-' + RIGHT('00' + CONVERT(VARCHAR(2), @Mes), 2), '-01'))
	SELECT @UltDia = CONVERT(CHAR(2), DAY(DATEADD(d, -1,DATEADD(M, 1, @DataIni))))		
	SELECT @DataFim = CONVERT(DATETIMEOFFSET, CONCAT(@Ano, '-', RIGHT('00' + CONVERT(VARCHAR(2), @Mes), 2), '-', @UltDia))
END