

--/************************************************************************
--	SCRIPT PARA DROPAR TODAS AS TABELAS NO WINDOWS AZURE
--************************************************************************/

---- DROP CONTRAINTS

--WHILE(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE='FOREIGN KEY'))
--BEGIN
--	DECLARE @SQL NVARCHAR(2000)
	
--	SELECT TOP 1 @SQL=('ALTER TABLE ' + TABLE_SCHEMA + '.[' + TABLE_NAME+ '] DROP CONSTRAINT [' + CONSTRAINT_NAME + ']')
--	FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
--	WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'
	
--	EXEC (@SQL)
--	PRINT @SQL
--END

--GO
----- DROP TABLES
--WHILE(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME != '__MIGRATIONHISTORY'))
--BEGIN
--	DECLARE @SQL NVARCHAR(2000)

--	SELECT TOP 1 @SQL=('DROP TABLE ' + TABLE_SCHEMA + '.[' + TABLE_NAME + ']')
--	FROM INFORMATION_SCHEMA.TABLES
--	WHERE TABLE_NAME != '__MIGRATIONHISTORY'
	
--	EXEC (@SQL)
--	PRINT @SQL
--END

--GO