@HostAddress = http://localhost:5140/api
# @HostAddress = https://ieadmauaapimembro.azurewebsites.net/api
@Token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIxIiwidW5pcXVlX25hbWUiOiJBUEkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9sb2NhbGl0eSI6IkFQSSIsIm5iZiI6MTczODYzMjYyMSwiZXhwIjoxNzM4NjM5ODIxLCJpYXQiOjE3Mzg2MzI2MjF9.t75ypztbL5ovest1Qq0A-yuYcgXTStpLqq-HbEVsrjQ

###
POST {{HostAddress}}/oauth/token
Content-Type: application/json

{
    "cpf": "857.677.795-97", 
    "senha": "abcdeeAf3@"
}

###
POST {{HostAddress}}/oauth/token
Content-Type: application/json

{
    "cpf": "aschurch_user", 
    "senha": "cba78f6e-669c-4bc1-a7fa-3cbeee1ab265"
}

###
GET {{HostAddress}}/Membro/consultarMembro?id=25024
Authorization: {{Token}}

###
PATCH  {{HostAddress}}/Membro/atualizarSenha
Authorization: {{Token}}
Content-Type: application/json

{
    "Id": "23714", 
    "NovaSenha": "nei06331"
}

###
PATCH  {{HostAddress}}/Membro/validarAtualizarSenha
Authorization: {{Token}}
Content-Type: application/json

{
    "Id": "14170", 
    "senhaAtual": "205489",
    "NovaSenha": "nei06331"
}

###
POST {{HostAddress}}/Membro/inscricao
Authorization: {{Token}}
Content-Type: application/json

{
    "cpf": "857.677.795-97",
    "nomeMae": "Regina",
    "email": "dennerpk@gmail.com",
    "dataNascimento": "2023-05-17"
}

###
POST {{HostAddress}}/Membro/recuperarSenha
Authorization: {{Token}}
Content-Type: application/json

{
    "cpf": "155.969.348-79"   
}

//id pastor 795
//id membro 14170
###
GET {{HostAddress}}/Membro/carteirinhaFrente?id=14170
Authorization: {{Token}}

###
GET {{HostAddress}}/Membro/carteirinhaVerso?id=795
Authorization: {{Token}}
###
GET {{HostAddress}}/Membro/carteirinhaQrCode?id=3
Authorization: {{Token}}
###
###
GET {{HostAddress}}/Membro/consultaCompletaMembro?id=3
Authorization: {{Token}}

###
PATCH  {{HostAddress}}/Membro/atualizarMembroAtualizado
Authorization: {{Token}}
Content-Type: application/json

{
    "id": 3, 
    "membroAtualizado": true
   
}