@HostAddress = http://localhost:5140/api

###
POST {{HostAddress}}/oauth/token
Content-Type: application/json

{
    "cpf": "089.073.828-91", 
    "senha": "nei06332"
}

###
POST {{HostAddress}}/oauth/token
Content-Type: application/json

{
    "cpf": "aschurch_user", 
    "senha": "cba78f6e-669c-4bc1-a7fa-3cbeee1ab265"
}

###
GET {{HostAddress}}/Membro/consultarMembro?id=3
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIzIiwidW5pcXVlX25hbWUiOiJBcm5hbGRvIEFsZW5jYXIgRmVycmVpcmEgIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbG9jYWxpdHkiOiJJRUFELU1hdcOhIC0gU2VkZSIsIm5iZiI6MTczNTU5Njk4OCwiZXhwIjoxNzM1NjA0MTg4LCJpYXQiOjE3MzU1OTY5ODh9.1ebezP4AounlP0n7DoCZp-jRXzhaDz6PqvaVro1WTsM
###
PATCH  {{HostAddress}}/Membro/atualizarSenha
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIxIiwidW5pcXVlX25hbWUiOiJBUEkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9sb2NhbGl0eSI6IkFQSSIsIm5iZiI6MTczNTU4MzY4NSwiZXhwIjoxNzM1NTkwODg1LCJpYXQiOjE3MzU1ODM2ODV9.vE4TD11bRdVx1D4Wts55gMBMKDxGnE7n3zNSEW1I-VY
Content-Type: application/json

{
    "Id": "23714", 
    "SenhaAtual": "392083",
    "NovaSenha": "nei06331"
}

###
POST {{HostAddress}}/Membro/inscricao
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIxIiwidW5pcXVlX25hbWUiOiJBUEkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9sb2NhbGl0eSI6IkFQSSIsIm5iZiI6MTczNTU4MzY4NSwiZXhwIjoxNzM1NTkwODg1LCJpYXQiOjE3MzU1ODM2ODV9.vE4TD11bRdVx1D4Wts55gMBMKDxGnE7n3zNSEW1I-VY
Content-Type: application/json

{
    "cpf": "396.873.658-38",
    "nomeMae": "Maria",
    "dataNascimento": "2006-02-07",
    "email": "claudineijose@gmail.com"
    
}

###
POST {{HostAddress}}/Membro/recuperarSenha
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIzIiwidW5pcXVlX25hbWUiOiJBcm5hbGRvIEFsZW5jYXIgRmVycmVpcmEgIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbG9jYWxpdHkiOiJJRUFELU1hdcOhIC0gU2VkZSIsIm5iZiI6MTczNTU4MjI5MiwiZXhwIjoxNzM1NTg5NDkyLCJpYXQiOjE3MzU1ODIyOTJ9.laidhHhjI1u_U0P_SF9G2r3581geyh6H_K1HAN-nEW8
Content-Type: application/json

{
    "cpf": "489.791.718-20"   
}

###
GET {{HostAddress}}/Membro/carteirinhaFrente?id=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIzIiwidW5pcXVlX25hbWUiOiJBcm5hbGRvIEFsZW5jYXIgRmVycmVpcmEgIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbG9jYWxpdHkiOiJJRUFELU1hdcOhIC0gU2VkZSIsIm5iZiI6MTczNTYwNTY1MywiZXhwIjoxNzM1NjEyODUzLCJpYXQiOjE3MzU2MDU2NTN9.tZEc9Z2x9HbWRU_6Cy91lXB-2lTHs-FoW6_vRDJiVV4

###
GET {{HostAddress}}/Membro/carteirinhaVerso?id=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIzIiwidW5pcXVlX25hbWUiOiJBcm5hbGRvIEFsZW5jYXIgRmVycmVpcmEgIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbG9jYWxpdHkiOiJJRUFELU1hdcOhIC0gU2VkZSIsIm5iZiI6MTczNTYwNTY1MywiZXhwIjoxNzM1NjEyODUzLCJpYXQiOjE3MzU2MDU2NTN9.tZEc9Z2x9HbWRU_6Cy91lXB-2lTHs-FoW6_vRDJiVV4
