CREATE PROCEDURE [dbo].[BuscarMembro]
	@PAGESIZE INT,
	@ROWSTART INT,
	@CAMPO VARCHAR(255) = NULL,
	@VALOR VARCHAR(255) = NULL
AS
BEGIN
	SET NOCOUNT ON
	DECLARE 
		@SQLQUERY NVARCHAR(4000),
		@SQLFILTO NVARCHAR(4000),
		@PARMDEFINITION NVARCHAR(500),
		@SQLFILTROAUX NVARCHAR(4000),
		@ORDERBY NVARCHAR(400)

/* CONFIGURAÇÃO DO FILTRO */
	SET @SQLFILTO = ''
	SET @ORDERBY = 'Id'
	IF(@CAMPO = 'Nome')
		SET @ORDERBY = 'Nome'
		
	IF (NULLIF(@VALOR,'') IS NOT NULL)
	BEGIN
		IF(@CAMPO = 'Id' AND NULLIF(@VALOR,'') IS NOT NULL)
			SET @SQLFILTO = @SQLFILTO + ' AND (Id = CONVERT(INT, @VALOR))'
		ELSE IF(@CAMPO = 'Nome')
		BEGIN
			SET @SQLFILTO = @SQLFILTO + ' AND (CHARINDEX(@VALOR, Nome) > 0)'
			SET @ORDERBY = 'Nome'
		END
	END

	SET @SQLQUERY =
	'SELECT TOP(@PAGESIZE) * FROM (' +
		'SELECT '+
		'C.Id, C.Nome, ROW_NUMBER() OVER (ORDER BY ' + @ORDERBY + ') AS NUM '+
		'FROM Membro C WITH(NOLOCK) ' + 
		'WHERE 1 = 1 '+
		+ @SQLFILTO +--Adicionado este trecho, pois, o cálculo de linhas fica errado se utilizar filtros entre a subquery e a query externa
	') AS A '+
	'WHERE '+
		'NUM > @ROWSTART '

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/
	SET @SQLQUERY = @SQLQUERY + @SQLFILTO + ' ORDER BY ' + @ORDERBY

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/

	/* EXECUCAÇÃO DA QUERY */
	SET @PARMDEFINITION = '@PAGESIZE INT, @ROWSTART INT, @VALOR VARCHAR(255)'
	EXECUTE SP_EXECUTESQL @SQLQUERY, @PARMDEFINITION, @PAGESIZE, @ROWSTART, @VALOR


	--/*RETORNA A QUANTIDADE DE LINHAS TOTAIS COM O FILTRO*/
	DECLARE @SQLCOUNT NVARCHAR(4000)
	SET @SQLCOUNT = 'SELECT COUNT(*) AS ROWSCOUNT FROM Membro WITH(NOLOCK) '
    SET @SQLCOUNT = @SQLCOUNT + ' WHERE 1=1 ' + @SQLFILTO
	EXECUTE SP_EXECUTESQL @SQLCOUNT, @PARMDEFINITION,@PAGESIZE, @ROWSTART, @VALOR

END