CREATE PROCEDURE ListarMembrosPendencias
	@PAGESIZE INT,
	@ROWSTART INT,
	@SORTING VARCHAR(30),
	@USUARIOID INT
AS
BEGIN
	SET NOCOUNT ON
	DECLARE 
		@SQLQUERY NVARCHAR(4000),
		@SQLFILTO NVARCHAR(4000),
		@PARMDEFINITION NVARCHAR(500),
		@SQLFILTROAUX NVARCHAR(4000),
		@ORDERBY NVARCHAR(400)

	/* CONFIGURAÇÃO DO FILTRO */
	SET @SQLFILTO = ''
	IF (CHARINDEX('CongregacaoId', @SORTING) > 0)
		SET @ORDERBY = REPLACE(@SORTING, 'CongregacaoId', 'C.Nome')
	ELSE
		SET @ORDERBY = 'M.' + ISNULL(@SORTING, 'Id ASC') 

	
	SET @SQLQUERY =
	'SELECT TOP(@PAGESIZE) * FROM (' +
		'SELECT '+
		'M.Id, M.Nome, M.NomeMae, M.Status, C.Nome AS CongregacaoNome, M.Cpf,  '+
		'ROW_NUMBER() OVER (ORDER BY ' + @ORDERBY + ') AS NUM '+
		'FROM Membro M WITH(NOLOCK) ' + 
		'INNER JOIN Congregacao C WITH(NOLOCK) ON C.Id = M.CongregacaoId ' +
		'WHERE ' +
		' M.CongregacaoId IN (SELECT * FROM dbo.CongregacaoAcesso(@USUARIOID, default)) ' +
		' AND Status IN (3, 4)'
		+ @SQLFILTO +
	') AS A '+
	'WHERE '+
		'NUM > @ROWSTART '

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/
	IF (CHARINDEX('CongregacaoId', @SORTING) > 0)
		SET @SQLQUERY = @SQLQUERY + ' ORDER BY ' + REPLACE(@SORTING, 'CongregacaoId', 'A.CongregacaoNome')
	ELSE
		SET @SQLQUERY = @SQLQUERY + ' ORDER BY A.' + REPLACE(@ORDERBY, 'M.', '')

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/

	/* EXECUCAÇÃO DA QUERY */
	SET @PARMDEFINITION = '@PAGESIZE INT, @ROWSTART INT, @USUARIOID INT'
	EXECUTE SP_EXECUTESQL @SQLQUERY, @PARMDEFINITION, @PAGESIZE, @ROWSTART, @USUARIOID


	--/*RETORNA A QUANTIDADE DE LINHAS TOTAIS COM O FILTRO*/
	DECLARE @SQLCOUNT NVARCHAR(4000)
	SET @SQLCOUNT = 'SELECT COUNT(*) AS ROWSCOUNT FROM Membro M WITH(NOLOCK) '
    SET @SQLCOUNT = @SQLCOUNT + ' WHERE M.CongregacaoId IN (SELECT * FROM dbo.CongregacaoAcesso(@USUARIOID, default)) AND Status IN (3, 4) ' + @SQLFILTO
	EXECUTE SP_EXECUTESQL @SQLCOUNT, @PARMDEFINITION, @PAGESIZE, @ROWSTART, @USUARIOID

END