CREATE PROCEDURE ListarMembroPaginada
	@PAGESIZE INT,
	@ROWSTART INT,
	@SORTING VARCHAR(30),
	@USUARIOID INT,
	@CAMPO VARCHAR(255) = NULL,
	@VALOR VARCHAR(255) = NULL,
	@TIPOMEMBRO INT = NULL,
	@STATUS INT = NULL
AS
BEGIN
	SET NOCOUNT ON
	DECLARE 
		@SQLQUERY NVARCHAR(4000),
		@SQLFILTO NVARCHAR(4000),
		@PARMDEFINITION NVARCHAR(500),
		@SQLFILTROAUX NVARCHAR(4000),
		@ORDERBY NVARCHAR(400)

	/* CONFIGURAÇÃO DO FILTRO */
	SET @SQLFILTO = ''
	IF (CHARINDEX('CongregacaoId', @SORTING) > 0)
		SET @ORDERBY = REPLACE(@SORTING, 'CongregacaoId', 'C.Nome')
	ELSE
		SET @ORDERBY = 'M.' + ISNULL(@SORTING, 'Id ASC') 
		
	IF (NULLIF(@VALOR,'') IS NOT NULL)
	BEGIN
		IF (@CAMPO = 'CongregacaoId')
			SET @SQLFILTO = @SQLFILTO + ' AND (CongregacaoId = @VALOR)'
		ELSE
			SET @SQLFILTO = @SQLFILTO + ' AND M.' + @CAMPO + ' LIKE ''%' + @VALOR + '%'' COLLATE Latin1_General_CI_AI'
	END
	IF (NULLIF(@TIPOMEMBRO, 0) IS NOT NULL)
		SET @SQLFILTO = @SQLFILTO + ' AND (M.TipoMembro = ' + CONVERT(VARCHAR(1), @TIPOMEMBRO) + ')'
	
	IF (NULLIF(@STATUS, 0) IS NOT NULL)
		SET @SQLFILTO = @SQLFILTO + ' AND (M.Status = ' + CONVERT(VARCHAR(1), @STATUS) + ')'

	SET @SQLQUERY =
	'SELECT TOP(@PAGESIZE) * FROM (' +
		'SELECT '+
		'M.Id, M.Nome, M.NomeMae, M.Status, C.Nome AS CongregacaoNome, M.Cpf,  '+
		'ROW_NUMBER() OVER (ORDER BY ' + @ORDERBY + ') AS NUM '+
		'FROM Membro M WITH(NOLOCK) ' + 
		'INNER JOIN Congregacao C WITH(NOLOCK) ON C.Id = M.CongregacaoId ' +
		'WHERE ' +
		' M.CongregacaoId IN (SELECT * FROM dbo.CongregacaoAcesso(@USUARIOID, default)) ' +
		+ @SQLFILTO +
	') AS A '+
	'WHERE '+
		'NUM > @ROWSTART '

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/
	IF (CHARINDEX('CongregacaoId', @SORTING) > 0)
		SET @SQLQUERY = @SQLQUERY + ' ORDER BY ' + REPLACE(@SORTING, 'CongregacaoId', 'A.CongregacaoNome')
	ELSE
		SET @SQLQUERY = @SQLQUERY + ' ORDER BY A.' + REPLACE(@ORDERBY, 'M.', '')

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/

	/* EXECUCAÇÃO DA QUERY */
	SET @PARMDEFINITION = '@PAGESIZE INT, @ROWSTART INT, @VALOR VARCHAR(255), @USUARIOID INT'
	EXECUTE SP_EXECUTESQL @SQLQUERY, @PARMDEFINITION, @PAGESIZE, @ROWSTART, @VALOR, @USUARIOID


	--/*RETORNA A QUANTIDADE DE LINHAS TOTAIS COM O FILTRO*/
	DECLARE @SQLCOUNT NVARCHAR(4000)
	SET @SQLCOUNT = 'SELECT COUNT(*) AS ROWSCOUNT FROM Membro M WITH(NOLOCK) '
    SET @SQLCOUNT = @SQLCOUNT + ' WHERE M.CongregacaoId IN (SELECT * FROM dbo.CongregacaoAcesso(@USUARIOID, default)) ' + @SQLFILTO
	EXECUTE SP_EXECUTESQL @SQLCOUNT, @PARMDEFINITION,@PAGESIZE, @ROWSTART, @VALOR, @USUARIOID

END