CREATE PROCEDURE ListarNascimentosPaginada
	@PAGESIZE INT,
	@ROWSTART INT,
	@SORTING VARCHAR(30),
	@USUARIOID INT,
	@CAMPO VARCHAR(255) = NULL,
	@VALOR VARCHAR(255) = NULL
AS
BEGIN
	SET NOCOUNT ON
	DECLARE 
		@SQLQUERY NVARCHAR(4000),
		@FILTRO NVARCHAR(4000),
		@PARMDEFINITION NVARCHAR(500),
		@SQLFILTROAUX NVARCHAR(4000),
		@ORDERBY NVARCHAR(400)

	/* CONFIGURAÇÃO DO FILTRO */
	SET @FILTRO = ''
	SET @ORDERBY = ISNULL(@SORTING, 'Id') 
		
	IF (NULLIF(@VALOR,'') IS NOT NULL)
		SET @FILTRO = @FILTRO + ' AND ' + @CAMPO + ' LIKE ''%' + @VALOR + '%'' COLLATE Latin1_General_CI_AI'

	SET @SQLQUERY =
	'SELECT TOP(@PAGESIZE) * FROM (' +
		'SELECT '+
		'N.Id,N.NomePai,N.NomeMae,N.Crianca,N.Sexo,N.CongregacaoID,N.DataNascimento,'+
		'N.DataApresentacao,N.DataCriacao,N.DataAlteracao,N.Pastor,N.PastorId,'+
		'ROW_NUMBER() OVER (ORDER BY N.' + @ORDERBY + ') AS NUM '+
		'From Nascimento N WITH(NOLOCK) ' + 
		'WHERE ' +
		' CongregacaoId IN (SELECT * FROM dbo.CongregacaoAcesso(@USUARIOID, default)) ' +
		+ @FILTRO +
	') AS A '+
	'WHERE '+
		'NUM > @ROWSTART '

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/
	SET @SQLQUERY = @SQLQUERY + @FILTRO + ' ORDER BY ' + @ORDERBY

	/* CONFIGURAÇÃO DA ORDENAÇÃO*/

	/* EXECUCAÇÃO DA QUERY */
	SET @PARMDEFINITION = '@PAGESIZE INT, @ROWSTART INT, @VALOR VARCHAR(255), @USUARIOID INT'
	EXECUTE SP_EXECUTESQL @SQLQUERY, @PARMDEFINITION, @PAGESIZE, @ROWSTART, @VALOR, @USUARIOID


	--/*RETORNA A QUANTIDADE DE LINHAS TOTAIS COM O FILTRO*/
	DECLARE @SQLCOUNT NVARCHAR(4000)
	SET @SQLCOUNT = 'SELECT COUNT(*) AS ROWSCOUNT FROM Nascimento N WITH(NOLOCK) '
    SET @SQLCOUNT = @SQLCOUNT + ' WHERE CongregacaoId IN (SELECT * FROM dbo.CongregacaoAcesso(@USUARIOID, default)) ' + @FILTRO
	EXECUTE SP_EXECUTESQL @SQLCOUNT, @PARMDEFINITION,@PAGESIZE, @ROWSTART, @VALOR, @USUARIOID

END